### ISSUE TITLE
Issue with changing laser zFocus

### ISSUE THREAD

**Issue by nepacheco** [ankrh/MCmatlab#1]
I am using MCmatlab on my GPU to simulate the effect of a laser fiber heating up a tissue. At each time step, if I only adjust the laser power, I can simulate 10 seconds of laser exposure in 0.01 second increments. 
For a second experiment, I wanted to vary the distance the laser was away from the tissue. I held the laser power constant and changed the parameter model.MC.beam.zFocus to the distance I wanted. Upon doing this, I get this error:

"GPUassert: an illegal memory access was encountered C:/Users/Anders/Documents/MCmatlab/+MCmatlab/src/MCmatlab_CUDA.cu 556 "

and MATLAB freezes.

**Comment by ankrh** [comment]
Dear Nicholas

Can you send me the model file that causes the crash?

BR Anders


From: Nicholas Pacheco ***@***.***>
Sent: 3. juni 2022 15:37
To: ankrh/MCmatlab ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [ankrh/MCmatlab] Issue with changing laser zFocus (Issue #1)


I am using MCmatlab on my GPU to simulate the effect of a laser fiber heating up a tissue. At each time step, if I only adjust the laser power, I can simulate 10 seconds of laser exposure in 0.01 second increments.
For a second experiment, I wanted to vary the distance the laser was away from the tissue. I held the laser power constant and changed the parameter model.MC.beam.zFocus to the distance I wanted. Upon doing this, I get this error:

"GPUassert: an illegal memory access was encountered C:/Users/Anders/Documents/MCmatlab/+MCmatlab/src/MCmatlab_CUDA.cu 556 "

and MATLAB freezes.

**Comment by nepacheco** [comment]
[ModelFiles.zip](https://github.com/ankrh/MCmatlab/files/8832848/ModelFiles.zip)
I think these are the relevant files. tempSingleStep.m is what we are calling to set the height. I also included model.m and makeTemperatureModel() which creates our model we then edit.

**Comment by ankrh** [comment]
Dear Nicholas

I tried running your model but I’m not sure what parameters you would normally pass into tempSingleStep.
Is it possible for you to isolate the crash to a particular set of parameters (a particular model)? If you can construct for me a single m-file that I can run directly that causes the crash, I can start to try to find the bug.

Best regards
Anders

**Comment by nepacheco** [comment]
I took a closer look at the issue I was having. It was coming from the geometry.m file. But, it seems the issue was caused by creating a zFocus of 'Inf' (trying to move the laser fiber as far away as possible from the tissue, instead of just shutting it off). 

So I think the issue has been resolved. Since eliminating infinite laser heights, I haven't encountered the issue.

One final quick question, though. The field model.MC.beam.NF.width represents the beam waist at its focus position, correct?  So, increasing the zFocus will increase the spot size on the tissue following the relationship 
          spot_size = beam_waist*sqrt(1 + (zFocus* lambda/(pi*beam_waist^2))^2)
where lambda is the wavelength of the laser. 
Am I understanding how these parameters interact correctly?

**Comment by ankrh** [comment]
Dear Nicholas

Excellent! I will implement some validation of input parameters soon to avoid the confusion of setting parameters like zFocus to an invalid value of Inf.

Regarding the spot size, your understanding is correct.

BR Anders

**Comment by nepacheco** [comment]
[ChangingHeight.zip](https://github.com/ankrh/MCmatlab/files/8903470/ChangingHeight.zip)
So I tried to manipulate the height of the laser and I am not getting any different results. When i adjust the spot size of the laser the tissue will change its response to the laser being on. 
I have attached my code with everything except MCmatlab because of github's size limits. The script to run is testTempControlAdaptive. On line 116 I set the height value. I have tried setting a height of 0, -10000, and 10000 and I get the same temperature response on the tissue. The actual model zFocus gets set in tempSingleStep line 82. I can't tell if I am accidentally overwriting the zFocus value somewhere or if it is just not being used.

**Comment by ankrh** [comment]
Alright, I will try to take a look as soon as I find time.

BR Anders

**Comment by ankrh** [comment]
Hi again Nicholas

Did you set the divergence of the beam correctly? That is, model.MC.beam.FF.radialWidth? It seems that you’ve set it to zero, which means that the beam will not diverge as it propagates. That means that even though you change the height of the laser (position of zFocus), it will have no influence on the light distribution entering the tissue. In other words, you’re working with a perfectly collimated beam.

Please let me know if I’ve misunderstood your code.

BR Anders

**Comment by nepacheco** [comment]
Thank you so much. That worked. I didn't realize I had to set the FarField parameters.
