### ISSUE TITLE
Setting model.HS.silentMode = true produces a runtime error

### ISSUE THREAD

**Issue by kid-a** [ankrh/MCmatlab#11]
Hi!

I downloaded version 4.4.0 from the Matlab Exchange and attempted to run Example #4 (https://github.com/ankrh/MCmatlab/blob/Release/Example4_BloodVessel.m). I commented out line 76 (https://github.com/ankrh/MCmatlab/blob/Release/Example4_BloodVessel.m#L76), and added `model.HS.silentMode = true;`

At runtime, I get the following error:

```
Arrays have incompatible sizes for this operation.

Error in MCmatlab.model/simulateHeatDistribution (line 67)
  if model.HS.silentMode && ~any(G.optTdependent(:) | G.thmTdependent(:) | G.optFDdependent(:) | G.thmFDdependent(:))

Error in Example4_BloodVessel (line 97)
model = simulateHeatDistribution(model);
```

**Comment by ankrh** [comment]
Hi and thanks for the bug report! I think I have fixed it now, it was a simple mistake :)

Check out the new 4.4.1 release.

- Anders

**Comment by kid-a** [comment]
Appreciate it! Thank you. :)
