### ISSUE TITLE
MATLAB drive

### ISSUE THREAD

**Issue by nvdbeekNL** [ankrh/MCmatlab#17]
Dear Anders and Dominik,

In the 4.4.4 version I'm getting an error relating to MATLAB drive. I run MCmatlab locally, so I wouldn't expect it to be used. 

The error message is:

Error using matlabdrive
matlabdrive is not supported because MATLAB Drive is not available.

Error in MCmatlab.model/plotMCmatlabGeom (line 30)
if strcmp(matlabdrive,'/MATLAB Drive') && strcmp(matlabroot, '/MATLAB')

Error in MCmatlab.model/plot (line 123)
          obj = plotMCmatlabGeom(obj);

Error in Copy2_of_Example4_BloodVessel (line 48)
model = plot(model,'G');

Related documentation

Is this a bug that needs to be quashed? Or is there something new in the settings I should adjust?

As always I'm grateful for all the time and effort you are putting into this project.

Thanks in advance for your help.

**Comment by DrDonik** [comment]
Thanks for the bug report!
This was indeed a bug introduced in version 4.4.3. It should be fixed now. If not, let us know.
Happy simulating
