### ISSUE TITLE
I get no progress of MC simulation for monochromatic light

### ISSUE THREAD

**Issue by ProjectEli** [ankrh/MCmatlab#26]
Previously, I got fixed version from issue #22. It works like a charm for broadband wavelengths. To isolate the wavelength-specific depth traces, I attempted to simulate monochromatic light. However, changing from an array of wavelength to a scalar value caused siulation to freeze at 0%. Reverting to broadband wavelengths restored normal operation as usual.

Memory trace for broadband simulation: memory increases as progress increases
`model.MC.wavelength=350:850;`
![image](https://github.com/user-attachments/assets/227e1678-84e7-40a2-8687-619c8a515739)

Memory trace for monochromatic simulation: progress stuck at 0% and no memory increase and no GPU load but somehow CPU has some loads. (CPU <10% when idle)
`model.MC.wavelength=550;`
![image](https://github.com/user-attachments/assets/8fa8dcf4-ce3e-4187-a2bc-3dc4363083e6)

What I got from broadband simulation (refined NormalizedFluenceRate data)
![image](https://github.com/user-attachments/assets/790b3f9e-e1a0-48f8-938a-1140de6c64c8)

I want to produce same data for monochromatic light source. What are causes and solutions?

**Comment by ankrh** [comment]
That's unexpected and must be some sort of bug. Can you share with me a model file that has this problem, so I can try to diagnose it?
