### ISSUE TITLE
Simulating Heat Distribution of Point Sources in a 3D Space

### ISSUE THREAD

**Issue by htyangs** [ankrh/MCmatlab#6]
Hi, I have a question regarding the use of point sources. In my scenario, I am distributing these sources within a 3D space, with the z-axis ranging from 0 to 15. If I want to simulate the heat diffusion, would it be acceptable to directly utilize the model's "MC.P" attribute [W] to represent my power? 
I ask this because, according to your description, the power is currently defined using infinite plane waves, which only accounts for the power incident upon the top surface of the cuboid.

**Comment by ankrh** [comment]
Thanks for the question! Allow me to clarify.

MC.P has a straightforward interpretation for all sources that are finite. The statement about infinite plane waves is just to explain how MC.P is interpreted *if* you select an infinite plane wave as your source.

So to answer your question: Yes, you can use MC.P in the straightforward way for your purpose.
