### ISSUE TITLE
MATLAB Library Incompatibility

### ISSUE THREAD

**Issue by jtzhangLogan** [ankrh/MCmatlab#8]
Hi, 

I met this problem when running the example.

```
Invalid MEX-file '~/MCmatlab/+MCmatlab/@model/private/MCmatlab.mexa64': libmwboost_filesystem.so.1.75.0: cannot open shared object file: No such file or directory
```

I am using R2023a and it carries ``libmwboost_filesystem.so.1.78.0``. Ideally, these two library should be compatible if the software versioning is standard. I wonder what could be the fix at this step.

Thank you!

**Comment by ankrh** [comment]
I will try to look into it. In the meantime you could try recompiling the code yourself (instructions are in the MCmatlab.c file) or using an older version of MATLAB

**Comment by ankrh** [comment]
I have made a new commit to the release branch in which I believe I have solved the issue. Please test it and let me know if it works.

Thanks for the bug report!

**Comment by jtzhangLogan** [comment]
Thank you so much for the update. It seems to have fixed the issue.
